# -*- coding: utf-8 -*-
"""Remotion 设计系统：色彩主题、平台画幅预设与规范库。"""

THEMES = {
    # ==================== 8 款主流沉浸暗色系 (Dark Themes) ====================
    "tech": {
        "name": "tech",
        "label": "前沿科技 (Tech Slate)",
        "isDark": True,
        "bg": "#090d16",
        "card_bg": "rgba(22, 30, 46, 0.85)",
        "surface": "rgba(22, 30, 46, 0.85)",
        "primary": "#38bdf8",
        "secondary": "#818cf8",
        "accent": "#06b6d4",
        "text": "#f8fafc",
        "text_muted": "#94a3b8",
        "muted": "#94a3b8",
        "border": "rgba(56, 189, 248, 0.25)",
        "glow": "rgba(56, 189, 248, 0.35)",
        "card_shadow": "0 20px 50px rgba(0, 0, 0, 0.5), 0 0 35px rgba(56, 189, 248, 0.2)",
    },
    "cyberpunk": {
        "name": "cyberpunk",
        "label": "赛博霓虹 (Cyberpunk)",
        "isDark": True,
        "bg": "#080312",
        "card_bg": "rgba(30, 10, 50, 0.8)",
        "surface": "rgba(30, 10, 50, 0.8)",
        "primary": "#f43f5e",
        "secondary": "#a855f7",
        "accent": "#06b6d4",
        "text": "#ffffff",
        "text_muted": "#c084fc",
        "muted": "#c084fc",
        "border": "rgba(244, 63, 94, 0.4)",
        "glow": "rgba(244, 63, 94, 0.5)",
        "card_shadow": "0 20px 50px rgba(0, 0, 0, 0.6), 0 0 35px rgba(244, 63, 94, 0.3)",
    },
    "finance": {
        "name": "finance",
        "label": "金融商业 (Finance Navy)",
        "isDark": True,
        "bg": "#06101e",
        "card_bg": "rgba(15, 29, 53, 0.85)",
        "surface": "rgba(15, 29, 53, 0.85)",
        "primary": "#10b981",
        "secondary": "#f59e0b",
        "accent": "#3b82f6",
        "text": "#f1f5f9",
        "text_muted": "#94a3b8",
        "muted": "#94a3b8",
        "border": "rgba(16, 185, 129, 0.3)",
        "glow": "rgba(16, 185, 129, 0.35)",
        "card_shadow": "0 20px 50px rgba(0, 0, 0, 0.55), 0 0 35px rgba(16, 185, 129, 0.2)",
    },
    "minimal": {
        "name": "minimal",
        "label": "极简高级黑 (Minimal Dark)",
        "isDark": True,
        "bg": "#121214",
        "card_bg": "rgba(28, 28, 32, 0.9)",
        "surface": "rgba(28, 28, 32, 0.9)",
        "primary": "#f4f4f5",
        "secondary": "#a1a1aa",
        "accent": "#71717a",
        "text": "#ffffff",
        "text_muted": "#a1a1aa",
        "muted": "#a1a1aa",
        "border": "rgba(255, 255, 255, 0.15)",
        "glow": "rgba(255, 255, 255, 0.15)",
        "card_shadow": "0 20px 50px rgba(0, 0, 0, 0.6)",
    },
    "business": {
        "name": "business",
        "label": "商务深蓝 (Corporate Blue)",
        "isDark": True,
        "bg": "#0b192c",
        "card_bg": "rgba(30, 62, 98, 0.8)",
        "surface": "rgba(30, 62, 98, 0.8)",
        "primary": "#2563eb",
        "secondary": "#60a5fa",
        "accent": "#38bdf8",
        "text": "#ffffff",
        "text_muted": "#cbd5e1",
        "muted": "#cbd5e1",
        "border": "rgba(37, 99, 235, 0.3)",
        "glow": "rgba(37, 99, 235, 0.4)",
        "card_shadow": "0 20px 50px rgba(0, 0, 0, 0.5), 0 0 35px rgba(37, 99, 235, 0.25)",
    },
    "education": {
        "name": "education",
        "label": "深翠学院 (Teal Mint)",
        "isDark": True,
        "bg": "#042023",
        "card_bg": "rgba(8, 48, 52, 0.85)",
        "surface": "rgba(8, 48, 52, 0.85)",
        "primary": "#2dd4bf",
        "secondary": "#fbbf24",
        "accent": "#14b8a6",
        "text": "#f0fdfa",
        "text_muted": "#99f6e4",
        "muted": "#99f6e4",
        "border": "rgba(45, 212, 191, 0.3)",
        "glow": "rgba(45, 212, 191, 0.35)",
        "card_shadow": "0 20px 50px rgba(0, 0, 0, 0.5), 0 0 35px rgba(45, 212, 191, 0.2)",
    },
    "lifestyle": {
        "name": "lifestyle",
        "label": "活力潮流 (Sunset Coral)",
        "isDark": True,
        "bg": "#1c0d12",
        "card_bg": "rgba(48, 20, 30, 0.85)",
        "surface": "rgba(48, 20, 30, 0.85)",
        "primary": "#fb7185",
        "secondary": "#fb923c",
        "accent": "#f43f5e",
        "text": "#fff1f2",
        "text_muted": "#fecdd3",
        "muted": "#fecdd3",
        "border": "rgba(251, 113, 133, 0.35)",
        "glow": "rgba(251, 113, 133, 0.4)",
        "card_shadow": "0 20px 50px rgba(0, 0, 0, 0.5), 0 0 35px rgba(251, 113, 133, 0.25)",
    },
    "gaming": {
        "name": "gaming",
        "label": "电竞先锋 (Gaming Emerald)",
        "isDark": True,
        "bg": "#050b06",
        "card_bg": "rgba(10, 26, 12, 0.85)",
        "surface": "rgba(10, 26, 12, 0.85)",
        "primary": "#22c55e",
        "secondary": "#eab308",
        "accent": "#ef4444",
        "text": "#f0fdf4",
        "text_muted": "#86efac",
        "muted": "#86efac",
        "border": "rgba(34, 197, 94, 0.35)",
        "glow": "rgba(34, 197, 94, 0.45)",
        "card_shadow": "0 20px 50px rgba(0, 0, 0, 0.6), 0 0 35px rgba(34, 197, 94, 0.3)",
    },

    # ==================== 8 款主流清新明亮浅色系 (Light Themes) ====================
    "clean_white": {
        "name": "clean_white",
        "label": "苹果极简白 (Clean White)",
        "isDark": False,
        "bg": "#f8fafc",
        "card_bg": "#ffffff",
        "surface": "#ffffff",
        "primary": "#0284c7",
        "secondary": "#6366f1",
        "accent": "#0ea5e9",
        "text": "#0f172a",
        "text_muted": "#64748b",
        "muted": "#64748b",
        "border": "rgba(203, 213, 225, 0.8)",
        "glow": "rgba(2, 132, 199, 0.12)",
        "card_shadow": "0 15px 40px rgba(15, 23, 42, 0.07), 0 2px 8px rgba(15, 23, 42, 0.04)",
    },
    "notion_light": {
        "name": "notion_light",
        "label": "Notion 纸墨暖白 (Notion Paper)",
        "isDark": False,
        "bg": "#faf7f2",
        "card_bg": "#ffffff",
        "surface": "#ffffff",
        "primary": "#d97706",
        "secondary": "#b45309",
        "accent": "#ea580c",
        "text": "#1c1917",
        "text_muted": "#78716c",
        "muted": "#78716c",
        "border": "rgba(214, 211, 209, 0.8)",
        "glow": "rgba(217, 119, 6, 0.12)",
        "card_shadow": "0 15px 40px rgba(41, 37, 36, 0.06), 0 2px 8px rgba(41, 37, 36, 0.03)",
    },
    "academic_light": {
        "name": "academic_light",
        "label": "高等学术雅白 (Academic Emerald)",
        "isDark": False,
        "bg": "#f4fbf7",
        "card_bg": "#ffffff",
        "surface": "#ffffff",
        "primary": "#059669",
        "secondary": "#0d9488",
        "accent": "#d97706",
        "text": "#064e3b",
        "text_muted": "#4b5563",
        "muted": "#4b5563",
        "border": "rgba(167, 243, 208, 0.85)",
        "glow": "rgba(5, 150, 105, 0.12)",
        "card_shadow": "0 15px 40px rgba(6, 78, 59, 0.06), 0 2px 8px rgba(6, 78, 59, 0.03)",
    },
    "corporate_light": {
        "name": "corporate_light",
        "label": "商务咨询雅白 (Corporate Clean)",
        "isDark": False,
        "bg": "#f1f5f9",
        "card_bg": "#ffffff",
        "surface": "#ffffff",
        "primary": "#1d4ed8",
        "secondary": "#0284c7",
        "accent": "#0891b2",
        "text": "#1e293b",
        "text_muted": "#64748b",
        "muted": "#64748b",
        "border": "rgba(203, 213, 225, 0.9)",
        "glow": "rgba(29, 78, 216, 0.12)",
        "card_shadow": "0 15px 40px rgba(30, 41, 59, 0.07), 0 2px 8px rgba(30, 41, 59, 0.03)",
    },
    "warm_editorial": {
        "name": "warm_editorial",
        "label": "人文杂志暖调 (Warm Editorial)",
        "isDark": False,
        "bg": "#fdfbf7",
        "card_bg": "#ffffff",
        "surface": "#ffffff",
        "primary": "#c2410c",
        "secondary": "#b45309",
        "accent": "#be123c",
        "text": "#292524",
        "text_muted": "#78716c",
        "muted": "#78716c",
        "border": "rgba(231, 229, 228, 0.95)",
        "glow": "rgba(194, 65, 12, 0.12)",
        "card_shadow": "0 15px 40px rgba(41, 37, 36, 0.06), 0 2px 8px rgba(41, 37, 36, 0.03)",
    },
    "fresh_mint": {
        "name": "fresh_mint",
        "label": "清新薄荷绿 (Fresh Mint)",
        "isDark": False,
        "bg": "#f0fdf4",
        "card_bg": "#ffffff",
        "surface": "#ffffff",
        "primary": "#10b981",
        "secondary": "#06b6d4",
        "accent": "#f59e0b",
        "text": "#0f172a",
        "text_muted": "#64748b",
        "muted": "#64748b",
        "border": "rgba(167, 243, 208, 0.85)",
        "glow": "rgba(16, 185, 129, 0.12)",
        "card_shadow": "0 15px 40px rgba(16, 185, 129, 0.07), 0 2px 8px rgba(16, 185, 129, 0.03)",
    },
    "sunset_light": {
        "name": "sunset_light",
        "label": "活力暖阳 (Sunset Amber)",
        "isDark": False,
        "bg": "#fffaf5",
        "card_bg": "#ffffff",
        "surface": "#ffffff",
        "primary": "#ea580c",
        "secondary": "#f59e0b",
        "accent": "#e11d48",
        "text": "#1c1917",
        "text_muted": "#78716c",
        "muted": "#78716c",
        "border": "rgba(254, 215, 170, 0.85)",
        "glow": "rgba(234, 88, 12, 0.12)",
        "card_shadow": "0 15px 40px rgba(234, 88, 12, 0.07), 0 2px 8px rgba(234, 88, 12, 0.03)",
    },
    "lavender_light": {
        "name": "lavender_light",
        "label": "梦幻香芋紫 (Lavender Dream)",
        "isDark": False,
        "bg": "#faf5ff",
        "card_bg": "#ffffff",
        "surface": "#ffffff",
        "primary": "#7c3aed",
        "secondary": "#c026d3",
        "accent": "#ec4899",
        "text": "#1e1b4b",
        "text_muted": "#6b7280",
        "muted": "#6b7280",
        "border": "rgba(233, 213, 255, 0.9)",
        "glow": "rgba(124, 58, 237, 0.12)",
        "card_shadow": "0 15px 40px rgba(124, 58, 237, 0.07), 0 2px 8px rgba(124, 58, 237, 0.03)",
    },

    # ==================== 4 款艺术与品牌定制调性 (Aesthetic & Brand Themes) ====================
    "morandi_mist": {
        "name": "morandi_mist",
        "label": "莫兰迪灰绿 (Morandi Mist)",
        "isDark": False,
        "bg": "#e9ede9",
        "card_bg": "rgba(255, 255, 255, 0.92)",
        "surface": "rgba(255, 255, 255, 0.92)",
        "primary": "#527365",
        "secondary": "#7e9f90",
        "accent": "#a38f78",
        "text": "#24332c",
        "text_muted": "#66776f",
        "muted": "#66776f",
        "border": "rgba(126, 159, 144, 0.45)",
        "glow": "rgba(82, 115, 101, 0.15)",
        "card_shadow": "0 15px 40px rgba(36, 51, 44, 0.06), 0 2px 8px rgba(36, 51, 44, 0.03)",
    },
    "luxury_gold": {
        "name": "luxury_gold",
        "label": "黑金奢华 (Luxury Black Gold)",
        "isDark": True,
        "bg": "#0c0d10",
        "card_bg": "rgba(24, 25, 30, 0.92)",
        "surface": "rgba(24, 25, 30, 0.92)",
        "primary": "#d4af37",
        "secondary": "#f3e5ab",
        "accent": "#e5c158",
        "text": "#ffffff",
        "text_muted": "#c5b8a5",
        "muted": "#c5b8a5",
        "border": "rgba(212, 175, 55, 0.35)",
        "glow": "rgba(212, 175, 55, 0.35)",
        "card_shadow": "0 20px 50px rgba(0, 0, 0, 0.7), 0 0 35px rgba(212, 175, 55, 0.2)",
    },
    "tiffany_cyan": {
        "name": "tiffany_cyan",
        "label": "蒂芙尼水青 (Tiffany Cyan)",
        "isDark": False,
        "bg": "#eaf7f6",
        "card_bg": "#ffffff",
        "surface": "#ffffff",
        "primary": "#0abab5",
        "secondary": "#0284c7",
        "accent": "#14b8a6",
        "text": "#0c3b39",
        "text_muted": "#487a78",
        "muted": "#487a78",
        "border": "rgba(10, 186, 181, 0.35)",
        "glow": "rgba(10, 186, 181, 0.15)",
        "card_shadow": "0 15px 40px rgba(12, 59, 57, 0.06), 0 2px 8px rgba(12, 59, 57, 0.03)",
    },
    "retro_film": {
        "name": "retro_film",
        "label": "复古胶片暖咖 (Retro Film)",
        "isDark": False,
        "bg": "#f4ede2",
        "card_bg": "#ffffff",
        "surface": "#ffffff",
        "primary": "#8c431d",
        "secondary": "#b45309",
        "accent": "#c2410c",
        "text": "#29180e",
        "text_muted": "#785848",
        "muted": "#785848",
        "border": "rgba(180, 83, 9, 0.3)",
        "glow": "rgba(140, 67, 29, 0.12)",
        "card_shadow": "0 15px 40px rgba(41, 24, 14, 0.06), 0 2px 8px rgba(41, 24, 14, 0.03)",
    },
}

PLATFORMS = {
    "youtube": {"name": "YouTube / 横屏 16:9", "width": 1920, "height": 1080, "aspect": "16:9"},
    "landscape": {"name": "标准横屏 16:9", "width": 1920, "height": 1080, "aspect": "16:9"},
    "tiktok": {"name": "TikTok / 竖屏 9:16", "width": 1080, "height": 1920, "aspect": "9:16"},
    "shorts": {"name": "Shorts / Reels 9:16", "width": 1080, "height": 1920, "aspect": "9:16"},
    "portrait": {"name": "标准竖屏 9:16", "width": 1080, "height": 1920, "aspect": "9:16"},
    "instagram_square": {"name": "社交方图 1:1", "width": 1080, "height": 1080, "aspect": "1:1"},
    "square": {"name": "标准方形 1:1", "width": 1080, "height": 1080, "aspect": "1:1"},
    "instagram_portrait": {"name": "社交竖版卡片 4:5", "width": 1080, "height": 1350, "aspect": "4:5"},
    "ultrawide": {"name": "电影级超宽屏 21:9", "width": 2560, "height": 1080, "aspect": "21:9"},
    "classic_4_3": {"name": "经典传统画幅 4:3", "width": 1440, "height": 1080, "aspect": "4:3"},
    "linkedin": {"name": "LinkedIn 商务视频 16:9", "width": 1920, "height": 1080, "aspect": "16:9"},
    "custom": {"name": "用户自定义像素画幅 (在 Spec 中指定 width 与 height)", "width": 0, "height": 0, "aspect": "custom"},
}

# 示例模板 Spec，供大模型直接参考
SAMPLE_SPECS = [
    {
        "id": "tech_product_launch",
        "title": "新一代 AI 智能体技术发布会",
        "theme": "tech",
        "platform": "youtube",
        "fps": 30,
        "spec": {
            "title": "新一代 AI 智能体技术发布会",
            "theme": "tech",
            "platform": "youtube",
            "fps": 30,
            "scenes": [
                {
                    "type": "TitleScene",
                    "duration": 4.0,
                    "title": "AGY-2.0 震撼发布",
                    "subtitle": "多模态全自主工程智能体系统",
                    "badge": "2026 KEYNOTE",
                    "variant": "gradient",
                    "animation": "fade_zoom",
                },
                {
                    "type": "BarChart",
                    "duration": 4.5,
                    "title": "自主编码与解决问题速度提升 (倍率)",
                    "data": [
                        {"label": "基线模型", "value": 1.0},
                        {"label": "v1.2", "value": 2.8},
                        {"label": "v1.5", "value": 6.4},
                        {"label": "v2.0", "value": 15.2},
                    ],
                },
                {
                    "type": "CodeBlock",
                    "duration": 4.5,
                    "title": "自主调用 Remotion 视频渲染",
                    "filename": "pipeline.ts",
                    "language": "typescript",
                    "code": 'const task = await agent.run({\n  prompt: "Generate product intro video",\n  theme: "tech",\n  output: "video.mp4"\n});\nconsole.log("Ready at: " + task.url);',
                },
                {
                    "type": "EndScreen",
                    "duration": 3.5,
                    "title": "开启智能体视频生产力",
                    "channel": "@RemotionStudio",
                    "cta": "即刻接入 MCP Server 体验",
                },
            ],
            "transition": {"type": "fade", "durationFrames": 12},
        },
    },
    {
        "id": "tiktok_data_insight",
        "title": "竖屏短视频：数字经济增长亮点",
        "theme": "finance",
        "platform": "tiktok",
        "fps": 30,
        "spec": {
            "title": "数字经济增长亮点",
            "theme": "finance",
            "platform": "tiktok",
            "fps": 30,
            "scenes": [
                {
                    "type": "TitleScene",
                    "duration": 3.5,
                    "title": "2026 数字经济速递",
                    "subtitle": "核心指标全景复盘",
                    "badge": "FINANCE FLASH",
                    "variant": "bold",
                    "animation": "slide_up",
                },
                {
                    "type": "HorizontalBarChart",
                    "duration": 4.5,
                    "title": "重点行业算力投资增速 (%)",
                    "data": [
                        {"label": "高端制造", "value": 68},
                        {"label": "金融科技", "value": 82},
                        {"label": "生物医药", "value": 95},
                        {"label": "具身智能", "value": 142},
                    ],
                },
                {
                    "type": "EndScreen",
                    "duration": 3.0,
                    "title": "点赞关注，获取每日洞察",
                    "channel": "@财智前沿",
                    "cta": "评论区获取完整研报",
                },
            ],
            "transition": {"type": "slide", "durationFrames": 10},
        },
    },
    {
        "id": "saas_quarterly_review",
        "title": "SaaS 核心业务指标与竞品对比复盘",
        "theme": "business",
        "platform": "youtube",
        "fps": 30,
        "spec": {
            "title": "SaaS 核心业务指标与竞品对比复盘",
            "theme": "business",
            "platform": "youtube",
            "fps": 30,
            "scenes": [
                {
                    "type": "TitleScene",
                    "duration": 3.5,
                    "title": "2026 Q3 战略经营成果",
                    "subtitle": "云原生多智能体平台全线突破",
                    "badge": "QUARTERLY BRIEF",
                    "variant": "gradient",
                },
                {
                    "type": "MetricCard",
                    "duration": 4.5,
                    "title": "核心经营数据指标",
                    "subtitle": "连续 4 个季度超预期达成目标",
                    "metrics": [
                        {
                            "label": "年度经常性收入 (ARR)",
                            "value": 48.6,
                            "prefix": "$",
                            "suffix": "M",
                            "change": "+142%",
                            "isPositive": True,
                            "changeLabel": "同比",
                            "helperText": "净收入留存率达 138%",
                        },
                        {
                            "label": "企业级付费客户",
                            "value": 1280,
                            "suffix": "+",
                            "change": "+85%",
                            "isPositive": True,
                            "changeLabel": "同比",
                            "helperText": "覆盖 60% 财富500强",
                        },
                        {
                            "label": "平均响应延迟",
                            "value": 42,
                            "suffix": "ms",
                            "change": "-64%",
                            "isPositive": True,
                            "changeLabel": "环比",
                            "helperText": "全球边缘加速节点赋能",
                        },
                    ],
                },
                {
                    "type": "ComparisonCard",
                    "duration": 5.0,
                    "title": "新一代多智能体协同引擎 vs 传统工作流",
                    "subtitle": "全链路自主推理与毫秒级渲染优势显著",
                    "vsBadge": "VS",
                    "left": {
                        "title": "传统脚本编排",
                        "subtitle": "手动配置 / 易碎性高",
                        "badge": "旧方案",
                        "isPositive": False,
                        "items": [
                            "模板单一呆板，缺乏动态物理缓动",
                            "渲染排队严重，高并发下频繁死锁",
                            "不支持 MCP 智能体端到端全自动生产",
                            "依赖笨重外部工具链，维护成本极高",
                        ],
                    },
                    "right": {
                        "title": "Remotion Studio Engine",
                        "subtitle": "AI 全自主驱动 / 像素级可控",
                        "badge": "创新突破",
                        "isPositive": True,
                        "items": [
                            "Spring 物理弹簧与高级贝塞尔曲线驱动",
                            "双模架构：声明式 Spec + 自由 TSX 源码",
                            "内置 Tini / SHM 2GB 生产级防泄露防崩",
                            "全协议适配：MCP SSE/HTTP + REST + Web UI",
                        ],
                    },
                },
                {
                    "type": "QuoteCard",
                    "duration": 4.0,
                    "quote": "Remotion Studio MCP 彻底颠覆了视频制作范式，智能体从提示词到成片只需短短数十秒，画质与动效堪比顶级设计团队。",
                    "author": "Alex Chen",
                    "title": "VP of Engineering @ CloudMatrix",
                    "avatar": "AC",
                },
                {
                    "type": "EndScreen",
                    "duration": 3.5,
                    "title": "开启智能视频创作时代",
                    "channel": "Remotion Studio Official",
                    "cta": "访问 GitHub 获取开源接入指引",
                },
            ],
            "transition": {"type": "fade", "durationFrames": 12},
        },
    },
    {
        "id": "product_roadmap_vision",
        "title": "产品演进路线与核心特性全览",
        "theme": "tech",
        "platform": "youtube",
        "fps": 30,
        "spec": {
            "title": "产品演进路线与核心特性全览",
            "theme": "tech",
            "platform": "youtube",
            "fps": 30,
            "scenes": [
                {
                    "type": "TitleScene",
                    "duration": 3.5,
                    "title": "Next-Gen 视频生产力体系",
                    "subtitle": "从数据看板到自由动效的全面跃迁",
                    "badge": "PRODUCT ROADMAP",
                },
                {
                    "type": "FeatureList",
                    "duration": 4.5,
                    "title": "四大核心工程特性",
                    "subtitle": "为大模型智能体量身定制的音视频基础设施",
                    "columns": 2,
                    "features": [
                        {
                            "title": "最新 Remotion 4.x 内核",
                            "description": "完整集成 Shapes, Paths, Transitions, Media-Utils 等官方全生态模块",
                            "badge": "Core",
                            "icon": "zap",
                        },
                        {
                            "title": "高性能异步架构",
                            "description": "异步并发信号量限流 + Chromium 僵尸回收 + 2GB 共享内存保护",
                            "badge": "Stability",
                            "icon": "shield",
                        },
                        {
                            "title": "多端画幅一键适配",
                            "description": "16:9 横屏、9:16 竖屏及 1:1 方形全场景自适应响应式布局",
                            "badge": "Design",
                            "icon": "sparkles",
                        },
                        {
                            "title": "极速流式交付",
                            "description": "HTTP 206 毫秒拖拽寻道播放，秒级生成高清海报封面与下载链接",
                            "badge": "Delivery",
                            "icon": "play",
                        },
                    ],
                },
                {
                    "type": "Timeline",
                    "duration": 5.0,
                    "title": "2026 技术路线里程碑",
                    "subtitle": "持续扩展多模态感知与音画合成能力",
                    "items": [
                        {
                            "date": "Q1 2026",
                            "title": "MCP & 双模引擎就绪",
                            "description": "声明式 Spec 与自由式 React 源码双模式跑通",
                            "badge": "已完成",
                            "active": False,
                        },
                        {
                            "date": "Q2 2026",
                            "title": "官方生态全量吸收",
                            "description": "Shapes / Paths / BGM / 10大商业级可视化组件",
                            "badge": "当前阶段",
                            "active": True,
                        },
                        {
                            "date": "Q3 2026",
                            "title": "多音轨与TTS音画对齐",
                            "description": "时间轴对齐、音量自动淡出、波形动态可视化",
                            "badge": "规划中",
                            "active": False,
                        },
                        {
                            "date": "Q4 2026",
                            "title": "分布式集群渲染",
                            "description": "GPU/硬件加速、分片并行渲染与秒级合成",
                            "badge": "展望",
                            "active": False,
                        },
                    ],
                },
                {
                    "type": "EndScreen",
                    "duration": 3.0,
                    "title": "与我们共同构建视频未来",
                    "channel": "Remotion Studio",
                    "cta": "星标项目 & 提交 PR",
                },
            ],
            "transition": {"type": "fade", "durationFrames": 12},
        },
    },
]

