# -*- coding: utf-8 -*-
"""Remotion 设计系统：色彩主题、平台画幅预设与规范库。"""

THEMES = {
    "tech": {
        "name": "tech",
        "label": "前沿科技 (Tech Slate)",
        "bg": "#090d16",
        "card_bg": "rgba(22, 30, 46, 0.8)",
        "primary": "#38bdf8",
        "secondary": "#818cf8",
        "accent": "#06b6d4",
        "text": "#f8fafc",
        "text_muted": "#94a3b8",
        "border": "rgba(56, 189, 248, 0.25)",
        "glow": "rgba(56, 189, 248, 0.35)",
    },
    "cyberpunk": {
        "name": "cyberpunk",
        "label": "赛博霓虹 (Cyberpunk)",
        "bg": "#080312",
        "card_bg": "rgba(30, 10, 50, 0.75)",
        "primary": "#f43f5e",
        "secondary": "#a855f7",
        "accent": "#06b6d4",
        "text": "#ffffff",
        "text_muted": "#c084fc",
        "border": "rgba(244, 63, 94, 0.4)",
        "glow": "rgba(244, 63, 94, 0.5)",
    },
    "finance": {
        "name": "finance",
        "label": "金融商业 (Finance Navy)",
        "bg": "#06101e",
        "card_bg": "rgba(15, 29, 53, 0.8)",
        "primary": "#10b981",
        "secondary": "#f59e0b",
        "accent": "#3b82f6",
        "text": "#f1f5f9",
        "text_muted": "#94a3b8",
        "border": "rgba(16, 185, 129, 0.3)",
        "glow": "rgba(16, 185, 129, 0.35)",
    },
    "minimal": {
        "name": "minimal",
        "label": "极简高级黑 (Minimal Dark)",
        "bg": "#121214",
        "card_bg": "rgba(28, 28, 32, 0.85)",
        "primary": "#f4f4f5",
        "secondary": "#a1a1aa",
        "accent": "#71717a",
        "text": "#ffffff",
        "text_muted": "#a1a1aa",
        "border": "rgba(255, 255, 255, 0.15)",
        "glow": "rgba(255, 255, 255, 0.15)",
    },
    "business": {
        "name": "business",
        "label": "商务深蓝 (Corporate Blue)",
        "bg": "#0b192c",
        "card_bg": "rgba(30, 62, 98, 0.75)",
        "primary": "#2563eb",
        "secondary": "#60a5fa",
        "accent": "#38bdf8",
        "text": "#ffffff",
        "text_muted": "#cbd5e1",
        "border": "rgba(37, 99, 235, 0.3)",
        "glow": "rgba(37, 99, 235, 0.4)",
    },
    "education": {
        "name": "education",
        "label": "知识学院 (Teal Mint)",
        "bg": "#042023",
        "card_bg": "rgba(8, 48, 52, 0.8)",
        "primary": "#2dd4bf",
        "secondary": "#fbbf24",
        "accent": "#14b8a6",
        "text": "#f0fdfa",
        "text_muted": "#99f6e4",
        "border": "rgba(45, 212, 191, 0.3)",
        "glow": "rgba(45, 212, 191, 0.35)",
    },
    "lifestyle": {
        "name": "lifestyle",
        "label": "活力潮流 (Sunset Coral)",
        "bg": "#1c0d12",
        "card_bg": "rgba(48, 20, 30, 0.8)",
        "primary": "#fb7185",
        "secondary": "#fb923c",
        "accent": "#f43f5e",
        "text": "#fff1f2",
        "text_muted": "#fecdd3",
        "border": "rgba(251, 113, 133, 0.35)",
        "glow": "rgba(251, 113, 133, 0.4)",
    },
    "gaming": {
        "name": "gaming",
        "label": "电竞先锋 (Gaming Emerald)",
        "bg": "#050b06",
        "card_bg": "rgba(10, 26, 12, 0.8)",
        "primary": "#22c55e",
        "secondary": "#eab308",
        "accent": "#ef4444",
        "text": "#f0fdf4",
        "text_muted": "#86efac",
        "border": "rgba(34, 197, 94, 0.35)",
        "glow": "rgba(34, 197, 94, 0.45)",
    },
}

PLATFORMS = {
    "youtube": {"name": "YouTube / 横屏 16:9", "width": 1920, "height": 1080, "aspect": "16:9"},
    "landscape": {"name": "标准横屏 16:9", "width": 1920, "height": 1080, "aspect": "16:9"},
    "tiktok": {"name": "TikTok / 竖屏 9:16", "width": 1080, "height": 1920, "aspect": "9:16"},
    "shorts": {"name": "Shorts / Reels 9:16", "width": 1080, "height": 1920, "aspect": "9:16"},
    "portrait": {"name": "标准竖屏 9:16", "width": 1080, "height": 1920, "aspect": "9:16"},
    "instagram_square": {"name": "社交方图 1:1", "width": 1080, "height": 1080, "aspect": "1:1"},
    "square": {"name": "标准方形 1:1", "width": 1080, "height": 1080, "aspect": "1:1"},
    "instagram_portrait": {"name": "社交竖版卡片 4:5", "width": 1080, "height": 1350, "aspect": "4:5"},
    "ultrawide": {"name": "电影级超宽屏 21:9", "width": 2560, "height": 1080, "aspect": "21:9"},
    "classic_4_3": {"name": "经典传统画幅 4:3", "width": 1440, "height": 1080, "aspect": "4:3"},
    "linkedin": {"name": "LinkedIn 商务视频 16:9", "width": 1920, "height": 1080, "aspect": "16:9"},
    "custom": {"name": "用户自定义像素画幅 (在 Spec 中指定 width 与 height)", "width": 0, "height": 0, "aspect": "custom"},
}

# 示例模板 Spec，供大模型直接参考
SAMPLE_SPECS = [
    {
        "id": "tech_product_launch",
        "title": "新一代 AI 智能体技术发布会",
        "theme": "tech",
        "platform": "youtube",
        "fps": 30,
        "spec": {
            "title": "新一代 AI 智能体技术发布会",
            "theme": "tech",
            "platform": "youtube",
            "fps": 30,
            "scenes": [
                {
                    "type": "TitleScene",
                    "duration": 4.0,
                    "title": "AGY-2.0 震撼发布",
                    "subtitle": "多模态全自主工程智能体系统",
                    "badge": "2026 KEYNOTE",
                    "variant": "gradient",
                    "animation": "fade_zoom",
                },
                {
                    "type": "BarChart",
                    "duration": 4.5,
                    "title": "自主编码与解决问题速度提升 (倍率)",
                    "data": [
                        {"label": "基线模型", "value": 1.0},
                        {"label": "v1.2", "value": 2.8},
                        {"label": "v1.5", "value": 6.4},
                        {"label": "v2.0", "value": 15.2},
                    ],
                },
                {
                    "type": "CodeBlock",
                    "duration": 4.5,
                    "title": "自主调用 Remotion 视频渲染",
                    "filename": "pipeline.ts",
                    "language": "typescript",
                    "code": 'const task = await agent.run({\n  prompt: "Generate product intro video",\n  theme: "tech",\n  output: "video.mp4"\n});\nconsole.log("Ready at: " + task.url);',
                },
                {
                    "type": "EndScreen",
                    "duration": 3.5,
                    "title": "开启智能体视频生产力",
                    "channel": "@RemotionStudio",
                    "cta": "即刻接入 MCP Server 体验",
                },
            ],
            "transition": {"type": "fade", "durationFrames": 12},
        },
    },
    {
        "id": "tiktok_data_insight",
        "title": "竖屏短视频：数字经济增长亮点",
        "theme": "finance",
        "platform": "tiktok",
        "fps": 30,
        "spec": {
            "title": "数字经济增长亮点",
            "theme": "finance",
            "platform": "tiktok",
            "fps": 30,
            "scenes": [
                {
                    "type": "TitleScene",
                    "duration": 3.5,
                    "title": "2026 数字经济速递",
                    "subtitle": "核心指标全景复盘",
                    "badge": "FINANCE FLASH",
                    "variant": "bold",
                    "animation": "slide_up",
                },
                {
                    "type": "HorizontalBarChart",
                    "duration": 4.5,
                    "title": "重点行业算力投资增速 (%)",
                    "data": [
                        {"label": "高端制造", "value": 68},
                        {"label": "金融科技", "value": 82},
                        {"label": "生物医药", "value": 95},
                        {"label": "具身智能", "value": 142},
                    ],
                },
                {
                    "type": "EndScreen",
                    "duration": 3.0,
                    "title": "点赞关注，获取每日洞察",
                    "channel": "@财智前沿",
                    "cta": "评论区获取完整研报",
                },
            ],
            "transition": {"type": "slide", "durationFrames": 10},
        },
    },
    {
        "id": "saas_quarterly_review",
        "title": "SaaS 核心业务指标与竞品对比复盘",
        "theme": "business",
        "platform": "youtube",
        "fps": 30,
        "spec": {
            "title": "SaaS 核心业务指标与竞品对比复盘",
            "theme": "business",
            "platform": "youtube",
            "fps": 30,
            "scenes": [
                {
                    "type": "TitleScene",
                    "duration": 3.5,
                    "title": "2026 Q3 战略经营成果",
                    "subtitle": "云原生多智能体平台全线突破",
                    "badge": "QUARTERLY BRIEF",
                    "variant": "gradient",
                },
                {
                    "type": "MetricCard",
                    "duration": 4.5,
                    "title": "核心经营数据指标",
                    "subtitle": "连续 4 个季度超预期达成目标",
                    "metrics": [
                        {
                            "label": "年度经常性收入 (ARR)",
                            "value": 48.6,
                            "prefix": "$",
                            "suffix": "M",
                            "change": "+142%",
                            "isPositive": True,
                            "changeLabel": "同比",
                            "helperText": "净收入留存率达 138%",
                        },
                        {
                            "label": "企业级付费客户",
                            "value": 1280,
                            "suffix": "+",
                            "change": "+85%",
                            "isPositive": True,
                            "changeLabel": "同比",
                            "helperText": "覆盖 60% 财富500强",
                        },
                        {
                            "label": "平均响应延迟",
                            "value": 42,
                            "suffix": "ms",
                            "change": "-64%",
                            "isPositive": True,
                            "changeLabel": "环比",
                            "helperText": "全球边缘加速节点赋能",
                        },
                    ],
                },
                {
                    "type": "ComparisonCard",
                    "duration": 5.0,
                    "title": "新一代多智能体协同引擎 vs 传统工作流",
                    "subtitle": "全链路自主推理与毫秒级渲染优势显著",
                    "vsBadge": "VS",
                    "left": {
                        "title": "传统脚本编排",
                        "subtitle": "手动配置 / 易碎性高",
                        "badge": "旧方案",
                        "isPositive": False,
                        "items": [
                            "模板单一呆板，缺乏动态物理缓动",
                            "渲染排队严重，高并发下频繁死锁",
                            "不支持 MCP 智能体端到端全自动生产",
                            "依赖笨重外部工具链，维护成本极高",
                        ],
                    },
                    "right": {
                        "title": "Remotion Studio Engine",
                        "subtitle": "AI 全自主驱动 / 像素级可控",
                        "badge": "创新突破",
                        "isPositive": True,
                        "items": [
                            "Spring 物理弹簧与高级贝塞尔曲线驱动",
                            "双模架构：声明式 Spec + 自由 TSX 源码",
                            "内置 Tini / SHM 2GB 生产级防泄露防崩",
                            "全协议适配：MCP SSE/HTTP + REST + Web UI",
                        ],
                    },
                },
                {
                    "type": "QuoteCard",
                    "duration": 4.0,
                    "quote": "Remotion Studio MCP 彻底颠覆了视频制作范式，智能体从提示词到成片只需短短数十秒，画质与动效堪比顶级设计团队。",
                    "author": "Alex Chen",
                    "title": "VP of Engineering @ CloudMatrix",
                    "avatar": "AC",
                },
                {
                    "type": "EndScreen",
                    "duration": 3.5,
                    "title": "开启智能视频创作时代",
                    "channel": "Remotion Studio Official",
                    "cta": "访问 GitHub 获取开源接入指引",
                },
            ],
            "transition": {"type": "fade", "durationFrames": 12},
        },
    },
    {
        "id": "product_roadmap_vision",
        "title": "产品演进路线与核心特性全览",
        "theme": "tech",
        "platform": "youtube",
        "fps": 30,
        "spec": {
            "title": "产品演进路线与核心特性全览",
            "theme": "tech",
            "platform": "youtube",
            "fps": 30,
            "scenes": [
                {
                    "type": "TitleScene",
                    "duration": 3.5,
                    "title": "Next-Gen 视频生产力体系",
                    "subtitle": "从数据看板到自由动效的全面跃迁",
                    "badge": "PRODUCT ROADMAP",
                },
                {
                    "type": "FeatureList",
                    "duration": 4.5,
                    "title": "四大核心工程特性",
                    "subtitle": "为大模型智能体量身定制的音视频基础设施",
                    "columns": 2,
                    "features": [
                        {
                            "title": "最新 Remotion 4.x 内核",
                            "description": "完整集成 Shapes, Paths, Transitions, Media-Utils 等官方全生态模块",
                            "badge": "Core",
                            "icon": "zap",
                        },
                        {
                            "title": "高性能异步架构",
                            "description": "异步并发信号量限流 + Chromium 僵尸回收 + 2GB 共享内存保护",
                            "badge": "Stability",
                            "icon": "shield",
                        },
                        {
                            "title": "多端画幅一键适配",
                            "description": "16:9 横屏、9:16 竖屏及 1:1 方形全场景自适应响应式布局",
                            "badge": "Design",
                            "icon": "sparkles",
                        },
                        {
                            "title": "极速流式交付",
                            "description": "HTTP 206 毫秒拖拽寻道播放，秒级生成高清海报封面与下载链接",
                            "badge": "Delivery",
                            "icon": "play",
                        },
                    ],
                },
                {
                    "type": "Timeline",
                    "duration": 5.0,
                    "title": "2026 技术路线里程碑",
                    "subtitle": "持续扩展多模态感知与音画合成能力",
                    "items": [
                        {
                            "date": "Q1 2026",
                            "title": "MCP & 双模引擎就绪",
                            "description": "声明式 Spec 与自由式 React 源码双模式跑通",
                            "badge": "已完成",
                            "active": False,
                        },
                        {
                            "date": "Q2 2026",
                            "title": "官方生态全量吸收",
                            "description": "Shapes / Paths / BGM / 10大商业级可视化组件",
                            "badge": "当前阶段",
                            "active": True,
                        },
                        {
                            "date": "Q3 2026",
                            "title": "多音轨与TTS音画对齐",
                            "description": "时间轴对齐、音量自动淡出、波形动态可视化",
                            "badge": "规划中",
                            "active": False,
                        },
                        {
                            "date": "Q4 2026",
                            "title": "分布式集群渲染",
                            "description": "GPU/硬件加速、分片并行渲染与秒级合成",
                            "badge": "展望",
                            "active": False,
                        },
                    ],
                },
                {
                    "type": "EndScreen",
                    "duration": 3.0,
                    "title": "与我们共同构建视频未来",
                    "channel": "Remotion Studio",
                    "cta": "星标项目 & 提交 PR",
                },
            ],
            "transition": {"type": "fade", "durationFrames": 12},
        },
    },
]

