# -*- coding: utf-8 -*-
"""Remotion 设计系统：色彩主题、平台画幅预设与规范库。"""

THEMES = {
    "tech": {
        "name": "tech",
        "label": "前沿科技 (Tech Slate)",
        "bg": "#090d16",
        "card_bg": "rgba(22, 30, 46, 0.8)",
        "primary": "#38bdf8",
        "secondary": "#818cf8",
        "accent": "#06b6d4",
        "text": "#f8fafc",
        "text_muted": "#94a3b8",
        "border": "rgba(56, 189, 248, 0.25)",
        "glow": "rgba(56, 189, 248, 0.35)",
    },
    "cyberpunk": {
        "name": "cyberpunk",
        "label": "赛博霓虹 (Cyberpunk)",
        "bg": "#080312",
        "card_bg": "rgba(30, 10, 50, 0.75)",
        "primary": "#f43f5e",
        "secondary": "#a855f7",
        "accent": "#06b6d4",
        "text": "#ffffff",
        "text_muted": "#c084fc",
        "border": "rgba(244, 63, 94, 0.4)",
        "glow": "rgba(244, 63, 94, 0.5)",
    },
    "finance": {
        "name": "finance",
        "label": "金融商业 (Finance Navy)",
        "bg": "#06101e",
        "card_bg": "rgba(15, 29, 53, 0.8)",
        "primary": "#10b981",
        "secondary": "#f59e0b",
        "accent": "#3b82f6",
        "text": "#f1f5f9",
        "text_muted": "#94a3b8",
        "border": "rgba(16, 185, 129, 0.3)",
        "glow": "rgba(16, 185, 129, 0.35)",
    },
    "minimal": {
        "name": "minimal",
        "label": "极简高级黑 (Minimal Dark)",
        "bg": "#121214",
        "card_bg": "rgba(28, 28, 32, 0.85)",
        "primary": "#f4f4f5",
        "secondary": "#a1a1aa",
        "accent": "#71717a",
        "text": "#ffffff",
        "text_muted": "#a1a1aa",
        "border": "rgba(255, 255, 255, 0.15)",
        "glow": "rgba(255, 255, 255, 0.15)",
    },
    "business": {
        "name": "business",
        "label": "商务深蓝 (Corporate Blue)",
        "bg": "#0b192c",
        "card_bg": "rgba(30, 62, 98, 0.75)",
        "primary": "#2563eb",
        "secondary": "#60a5fa",
        "accent": "#38bdf8",
        "text": "#ffffff",
        "text_muted": "#cbd5e1",
        "border": "rgba(37, 99, 235, 0.3)",
        "glow": "rgba(37, 99, 235, 0.4)",
    },
    "education": {
        "name": "education",
        "label": "知识学院 (Teal Mint)",
        "bg": "#042023",
        "card_bg": "rgba(8, 48, 52, 0.8)",
        "primary": "#2dd4bf",
        "secondary": "#fbbf24",
        "accent": "#14b8a6",
        "text": "#f0fdfa",
        "text_muted": "#99f6e4",
        "border": "rgba(45, 212, 191, 0.3)",
        "glow": "rgba(45, 212, 191, 0.35)",
    },
    "lifestyle": {
        "name": "lifestyle",
        "label": "活力潮流 (Sunset Coral)",
        "bg": "#1c0d12",
        "card_bg": "rgba(48, 20, 30, 0.8)",
        "primary": "#fb7185",
        "secondary": "#fb923c",
        "accent": "#f43f5e",
        "text": "#fff1f2",
        "text_muted": "#fecdd3",
        "border": "rgba(251, 113, 133, 0.35)",
        "glow": "rgba(251, 113, 133, 0.4)",
    },
    "gaming": {
        "name": "gaming",
        "label": "电竞先锋 (Gaming Emerald)",
        "bg": "#050b06",
        "card_bg": "rgba(10, 26, 12, 0.8)",
        "primary": "#22c55e",
        "secondary": "#eab308",
        "accent": "#ef4444",
        "text": "#f0fdf4",
        "text_muted": "#86efac",
        "border": "rgba(34, 197, 94, 0.35)",
        "glow": "rgba(34, 197, 94, 0.45)",
    },
}

PLATFORMS = {
    "youtube": {"name": "YouTube / 横屏 16:9", "width": 1920, "height": 1080, "aspect": "16:9"},
    "landscape": {"name": "标准横屏 16:9", "width": 1920, "height": 1080, "aspect": "16:9"},
    "tiktok": {"name": "TikTok / 竖屏 9:16", "width": 1080, "height": 1920, "aspect": "9:16"},
    "shorts": {"name": "Shorts / Reels 9:16", "width": 1080, "height": 1920, "aspect": "9:16"},
    "portrait": {"name": "标准竖屏 9:16", "width": 1080, "height": 1920, "aspect": "9:16"},
    "instagram_square": {"name": "方图 1:1", "width": 1080, "height": 1080, "aspect": "1:1"},
    "square": {"name": "标准方形 1:1", "width": 1080, "height": 1080, "aspect": "1:1"},
    "linkedin": {"name": "LinkedIn 视频", "width": 1920, "height": 1080, "aspect": "16:9"},
}

# 示例模板 Spec，供大模型直接参考
SAMPLE_SPECS = [
    {
        "id": "tech_product_launch",
        "title": "新一代 AI 智能体技术发布会",
        "theme": "tech",
        "platform": "youtube",
        "fps": 30,
        "spec": {
            "title": "新一代 AI 智能体技术发布会",
            "theme": "tech",
            "platform": "youtube",
            "fps": 30,
            "scenes": [
                {
                    "type": "TitleScene",
                    "duration": 4.0,
                    "title": "AGY-2.0 震撼发布",
                    "subtitle": "多模态全自主工程智能体系统",
                    "badge": "2026 KEYNOTE",
                    "variant": "gradient",
                    "animation": "fade_zoom",
                },
                {
                    "type": "BarChart",
                    "duration": 4.5,
                    "title": "自主编码与解决问题速度提升 (倍率)",
                    "data": [
                        {"label": "基线模型", "value": 1.0},
                        {"label": "v1.2", "value": 2.8},
                        {"label": "v1.5", "value": 6.4},
                        {"label": "v2.0", "value": 15.2},
                    ],
                },
                {
                    "type": "CodeBlock",
                    "duration": 4.5,
                    "title": "自主调用 Remotion 视频渲染",
                    "filename": "pipeline.ts",
                    "language": "typescript",
                    "code": 'const task = await agent.run({\n  prompt: "Generate product intro video",\n  theme: "tech",\n  output: "video.mp4"\n});\nconsole.log("Ready at: " + task.url);',
                },
                {
                    "type": "EndScreen",
                    "duration": 3.5,
                    "title": "开启智能体视频生产力",
                    "channel": "@RemotionStudio",
                    "cta": "即刻接入 MCP Server 体验",
                },
            ],
            "transition": {"type": "fade", "durationFrames": 12},
        },
    },
    {
        "id": "tiktok_data_insight",
        "title": "竖屏短视频：数字经济增长亮点",
        "theme": "finance",
        "platform": "tiktok",
        "fps": 30,
        "spec": {
            "title": "数字经济增长亮点",
            "theme": "finance",
            "platform": "tiktok",
            "fps": 30,
            "scenes": [
                {
                    "type": "TitleScene",
                    "duration": 3.5,
                    "title": "2026 数字经济速递",
                    "subtitle": "核心指标全景复盘",
                    "badge": "FINANCE FLASH",
                    "variant": "bold",
                    "animation": "slide_up",
                },
                {
                    "type": "HorizontalBarChart",
                    "duration": 4.5,
                    "title": "重点行业算力投资增速 (%)",
                    "data": [
                        {"label": "高端制造", "value": 68},
                        {"label": "金融科技", "value": 82},
                        {"label": "生物医药", "value": 95},
                        {"label": "具身智能", "value": 142},
                    ],
                },
                {
                    "type": "EndScreen",
                    "duration": 3.0,
                    "title": "点赞关注，获取每日洞察",
                    "channel": "@财智前沿",
                    "cta": "评论区获取完整研报",
                },
            ],
            "transition": {"type": "slide", "durationFrames": 10},
        },
    },
]
